// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkkqbdkkelexjozqfaaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJra3FiZGtrZWxleGpvenFmYWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTkxMjYsImV4cCI6MjA3Mjg5NTEyNn0.Q95O617qn4Au27ptsGPpLCSywyDpowok0EDsBeDLxII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});